Lab1
L0ckR/OS_LABS pull request #1
Opened 2023-09-27 07:04 UTC by L0ckR

2023-09-27 18:44 UTC, QElderDelta requested changes

2023-09-27 18:44 UTC, QElderDelta commented on lab1/include/parent.hpp
> +
Убери лишние пробелы

2023-09-27 18:44 UTC, QElderDelta commented on lab1/include/parent.hpp
> +#ifndef OS_LABS_PARENT_H
```#pragma once``` короче

2023-09-27 18:44 UTC, QElderDelta commented on lab1/include/parent.hpp
> +void parentProcess(std::string pathToChild, std::istream & streamIn, std::ostream & streamOut);
Зачем лишнее копирование строки? Либо ```const std::string&``` или вообще даже лучше ```std::string_view```

2023-09-27 18:44 UTC, QElderDelta commented on lab1/include/utils.hpp
> +// #include <signal.h>
Убери закомменченный код

2023-09-27 18:44 UTC, QElderDelta commented on lab1/include/utils.hpp
> +bool BothAreSpaces(char lhs, char rhs);
Названия всех функции написаны по-разному, по кодстайлу PascalCase

2023-09-27 18:44 UTC, QElderDelta commented on lab1/include/utils.hpp
> +void exec(std::string pathToChild);
Тот же самый комментарий про лишнее копирование

2023-09-27 18:44 UTC, QElderDelta commented on lab1/main.cpp
> +    parentProcess("../lab1/child", std::cin, std::cout);
Лучше поменять путь на перемнную окружения

2023-09-27 18:44 UTC, QElderDelta commented on lab1/src/child.cpp
> +    pid_t pid = createChild();
Родительский процесс создает два дочерних, а у тебя родительский создает дочерний и потом дочерний еще один дочерний. Надо поправить

2023-09-27 18:44 UTC, QElderDelta commented on lab1/src/child.cpp
> +// #include <utils.hpp>
Убери закомменченный код

2023-09-27 18:44 UTC, QElderDelta commented on lab1/src/child.cpp
> +            std::string::iterator new_end = std::unique(line.begin(), line.end(), BothAreSpaces);
Для таких типов есть ```auto```

2023-09-27 18:44 UTC, QElderDelta commented on lab1/src/utils.cpp
> +    if (execl(pathToChild.c_str(), "child", NULL) == -1) {
nullptr

2023-09-27 18:44 UTC, QElderDelta commented on lab1/src/utils.cpp
> +  __gnu_cxx::stdio_filebuf<char> filebuf(file_descriptor,
Прикольно, конечно, но давай все-таки read/write голые использовать, лаба же про системные вызовы

2023-09-27 18:44 UTC, QElderDelta commented on lab1/src/utils.cpp
> +            return (lhs == rhs) && (lhs == ' ');
Лучше ```std::isspace(lhs) && std::isspace(rhs)```

2023-09-27 18:44 UTC, QElderDelta commented on tests/lab1_test.cpp
> +    std::string fileWithInput = "input.txt";
Зачем тебе мучаться с файлами, если ты можешь в функцию ```std::stringstream``` передать

2023-09-27 18:44 UTC, QElderDelta commented on tests/lab1_test.cpp
> +    parentProcess("../lab1/child", inFile, outFile);
Было бы неплохо избавиться от захардкоженных путей

2023-09-27 18:44 UTC, QElderDelta commented on tests/lab1_test.cpp
> +    std::string fileWithInput = "input.txt";
Очень много дублирования кода, можно вынести в отдельную функцию всю логику и в нее просто передавать 2 вектора - что должно быть на входе и что должно быть на выходе

2023-09-27 21:47 UTC, L0ckR commented on lab1/include/parent.hpp
> +
убрал

2023-09-27 21:59 UTC, L0ckR commented on lab1/include/parent.hpp
> +void parentProcess(std::string pathToChild, std::istream & streamIn, std::ostream & streamOut);
решено в коммите 9f1c750f7db8077939c1e3342c7f1f4c4b784e1b

2023-09-27 22:00 UTC, L0ckR commented on lab1/include/utils.hpp
> +// #include <signal.h>
убрал
решено в коммите 95d928db0d23d39bb092be894368f8336771f0ce

2023-09-27 22:27 UTC, L0ckR commented on lab1/include/utils.hpp
> +bool BothAreSpaces(char lhs, char rhs);
all my homies prefer camelCase, но ладно

решено в коммите b42eac0e86d998e4cb45fc12ddaad0350f51b652

2023-09-27 22:30 UTC, L0ckR commented on lab1/include/parent.hpp
> +#ifndef OS_LABS_PARENT_H
решено в коммите b42eac0e86d998e4cb45fc12ddaad0350f51b652

2023-09-27 22:35 UTC, L0ckR commented on lab1/include/utils.hpp
> +void exec(std::string pathToChild);
решено в коммите 680d8d4e67b5dbc49e11aba3633d4360dd7ed32b

2023-09-27 22:40 UTC, L0ckR commented on lab1/main.cpp
> +    parentProcess("../lab1/child", std::cin, std::cout);
решено в df4c9f349fecca8faa1fc061db08a756aa53336f

2023-09-27 22:49 UTC, L0ckR commented on lab1/src/child.cpp
> +// #include <utils.hpp>
решено в 95d928db0d23d39bb092be894368f8336771f0ce

2023-09-27 22:50 UTC, L0ckR commented on lab1/src/utils.cpp
> +    if (execl(pathToChild.c_str(), "child", NULL) == -1) {
не понял что требуется

2023-09-27 22:52 UTC, L0ckR commented on tests/lab1_test.cpp
> +    parentProcess("../lab1/child", inFile, outFile);
решено в df4c9f349fecca8faa1fc061db08a756aa53336f

2023-09-28 00:40 UTC, L0ckR commented on lab1/src/utils.cpp
> +            return (lhs == rhs) && (lhs == ' ');
исправлено в коммите 090db550f5b2448b7b11999107b7061a79e139ee

2023-09-28 00:41 UTC, L0ckR commented on tests/lab1_test.cpp
> +    std::string fileWithInput = "input.txt";
получать в stringstream не особо получается, попробовал исправить в aba23af9e406b29c44c1991b974a5ecf9294995a 
получил segfault. не разобрался почему

2023-09-28 00:41 UTC, L0ckR commented on tests/lab1_test.cpp
> +    std::string fileWithInput = "input.txt";
исправлено в aba23af9e406b29c44c1991b974a5ecf9294995a

2023-09-28 00:42 UTC, L0ckR commented on lab1/src/child.cpp
> +            std::string::iterator new_end = std::unique(line.begin(), line.end(), BothAreSpaces);
испарвлено в 090db550f5b2448b7b11999107b7061a79e139ee

2023-09-28 00:43 UTC, L0ckR commented on lab1/src/utils.cpp
> +  __gnu_cxx::stdio_filebuf<char> filebuf(file_descriptor,
эххххххххххххххххххххххххххххххххххххххххх

2023-09-28 00:43 UTC, L0ckR commented on lab1/src/child.cpp
> +    pid_t pid = createChild();
исправлено в aba23af9e406b29c44c1991b974a5ecf9294995a

2023-09-30 17:26 UTC, L0ckR reviewed
new changes asked by QElderDelta

2023-10-01 11:37 UTC, QElderDelta approved these changes

2023-10-01 11:37 UTC, QElderDelta commented on lab1/src/parent.cpp
> +    std::streambuf* oldInBuf = std::cin.rdbuf(streamIn.rdbuf());
А почему не хочешь просто из streamIn читать и в streamOut писать? Не очень понимаю зачем с перекладыванием буфферов заморачиваться

2023-10-01 11:37 UTC, QElderDelta commented on lab1/src/parent.cpp
> +    int CHILD2_STDOUT[2];
Не по код стайлу перменная

2023-10-01 11:37 UTC, QElderDelta commented on lab1/src/parent.cpp
> +            write(CHILD1_STDIN[WRITE_END], line.c_str(), line.length());
.size() короче))

2023-10-01 11:37 UTC, QElderDelta commented on lab1/src/utils.cpp
> +    if( pid < 0 ){
Если хочешь, то можно использовать if с инициализацией
```
if(pid_t pid = fork(); pid >= 0) {
    return pid;
}
std::perror("Couldn't create child.");
exit(EXIT_FAILURE);   
```

2023-10-01 11:37 UTC, QElderDelta commented on lab1/src/utils.cpp
> +        int state = read(file_descriptor, &ch, sizeof(char));
Я думаю, что можно читать эффективнее не по одному байту, а кусками, например по 256 байт

2023-10-01 11:37 UTC, QElderDelta commented on lab1/src/utils.cpp
> +        int state = read(file_descriptor, &ch, sizeof(char));
Вся логика остается такой же

2023-10-01 11:37 UTC, QElderDelta commented on tests/lab1_test.cpp
> +    std::stringstream inFile(std::accumulate(input.begin(), input.end(), strSum, BindTwoStrings()));
Лучше пользоваться лямбда-функциями, они не плодят лишних сущностей

2023-10-01 11:37 UTC, QElderDelta commented on tests/lab1_test.cpp
> +        for(std::string expectation : expectedOutput) {
const std::string&

2023-10-01 11:37 UTC, QElderDelta commented on tests/lab1_test.cpp
> +    // выдает segfault в тестирующей оболочке vscode если затребоать переменную окружения
Потому что в ней эту саму переменную нужно выставить. Можешь проверить, что getenv возвращает nullptr

2023-10-01 11:37 UTC, QElderDelta commented on tests/lab1_test.cpp
> +    std::vector<std::string> input = {
const std::vector, чтобы совсем красиво было

2023-10-01 11:59 UTC, QElderDelta commented on tests/lab1_test.cpp
> +    if(fs::exists(getenv("PATH_TO_CHILD1")) & fs::exists(getenv("PATH_TO_CHILD2"))){
Два амперсанда

2023-10-01 12:01 UTC, QElderDelta commented on tests/lab1_test.cpp
> +void TestParent(std::vector<std::string> input, std::vector<std::string> expectedOutput){
```const std::vector<std::string>&```

2023-10-01 12:05 UTC, L0ckR commented on lab1/src/parent.cpp
> +    std::streambuf* oldInBuf = std::cin.rdbuf(streamIn.rdbuf());
исправлено в коммите 42ec6aec0d37b9942a0648478fe727b2d99c3fc8

2023-10-01 12:06 UTC, L0ckR commented on lab1/src/parent.cpp
> +            write(CHILD1_STDIN[WRITE_END], line.c_str(), line.length());
исправлено в c0e38ce617fe28d8574eb6a86026bb5b175358ef

2023-10-01 12:08 UTC, L0ckR commented on lab1/src/utils.cpp
> +    if( pid < 0 ){
изменено в d2f3724e6ad121a36fc80a9f06f128709b1ab88a

2023-10-01 12:14 UTC, QElderDelta commented on lab1/include/parent.hpp
> +void ParentProcess(std::string_view pathToChild1, std::string_view pathToChild2, std::istream & streamIn, std::ostream & streamOut);
Я дал плохой совет, лучше путь передавать как ```const char*```, чтобы в Exec не создавать строку и делать все то же лишнее копирование

2023-10-01 12:16 UTC, L0ckR commented on tests/lab1_test.cpp
> +    // выдает segfault в тестирующей оболочке vscode если затребоать переменную окружения
это  скорее для себя подпись, потому что я так и не нашел где запускаются тесты из vscode и где ему прописывать конфигурацию окружения

2023-10-01 12:17 UTC, L0ckR commented on tests/lab1_test.cpp
> +    // выдает segfault в тестирующей оболочке vscode если затребоать переменную окружения
я про эту шнягу
![image](https://github.com/L0ckR/OS_LABS/assets/71556621/03e27ba4-5dc4-4642-acbc-22cfbb20d8d2)

2023-10-01 12:20 UTC, L0ckR commented on lab1/include/parent.hpp
> +void ParentProcess(std::string_view pathToChild1, std::string_view pathToChild2, std::istream & streamIn, std::ostream & streamOut);
изменено в d38411730a52cae993fdbf344eae36bfccd538af

2023-10-01 12:20 UTC, L0ckR commented on tests/lab1_test.cpp
> +void TestParent(std::vector<std::string> input, std::vector<std::string> expectedOutput){
исправлено в d38411730a52cae993fdbf344eae36bfccd538af

2023-10-01 12:22 UTC, L0ckR commented on tests/lab1_test.cpp
> +    std::vector<std::string> input = {
испарвлено в 59b10f30c8b98037c864282f0ac3ee1f679a4fce

2023-10-01 12:22 UTC, L0ckR commented on tests/lab1_test.cpp
> +    if(fs::exists(getenv("PATH_TO_CHILD1")) & fs::exists(getenv("PATH_TO_CHILD2"))){
испарвлено в 59b10f30c8b98037c864282f0ac3ee1f679a4fce

2023-10-01 12:22 UTC, L0ckR commented on tests/lab1_test.cpp
> +        for(std::string expectation : expectedOutput) {
исправлено в d38411730a52cae993fdbf344eae36bfccd538af

2023-10-01 12:23 UTC, L0ckR commented on tests/lab1_test.cpp
> +    std::stringstream inFile(std::accumulate(input.begin(), input.end(), strSum, BindTwoStrings()));
испарвлено в d38411730a52cae993fdbf344eae36bfccd538af

2023-10-01 12:30 UTC, L0ckR commented on lab1/src/parent.cpp
> +    int CHILD2_STDOUT[2];
d5bf25f4786efd68f20fecbe71f8bc272aceff31

2023-10-01 12:51 UTC, L0ckR commented on lab1/src/utils.cpp
> +        int state = read(file_descriptor, &ch, sizeof(char));
испарвлено в 099e10ab3c1c4f9b1074d9ef69ce3bbcb39cd7e7

2023-10-01 12:52 UTC, L0ckR reviewed
new changes asked by QElderDelta

2023-10-01 12:52 UTC, merged