lab2 init
L0ckR/OS_LABS pull request #3
Opened 2023-10-11 23:54 UTC by L0ckR

2023-10-12 13:37 UTC, QElderDelta requested changes

2023-10-12 13:37 UTC, QElderDelta commented on lab2/include/monte-carlo.hpp
> +typedef struct{
Зачем typedef, ты же на плюсах пишешь, объяви сразу как
```cpp
struct <нужное_имя> {
...
};
```

2023-10-12 13:37 UTC, QElderDelta commented on lab2/include/monte-carlo.hpp
> +#define _USE_MATH_DEFINES
А это зачем?

2023-10-12 13:37 UTC, QElderDelta commented on CMakeLists.txt
> +#add LAB1
LAB2

2023-10-12 13:37 UTC, QElderDelta commented on lab2/CMakeLists.txt
> +# set(THREADS_PREFER_PTHREAD_FLAG ON)
Во-первых, закомменченный код. Во-вторых, как оно у тебя собирается, если ты pthread не линкуешь?

2023-10-12 13:37 UTC, QElderDelta commented on lab2/include/monte-carlo.hpp
> +bool IsInCircle(const Coordinats &cords, const double radius);
const для параметров, передаваемых по значению особо смысла не имеет

2023-10-12 13:37 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +    // if ((cords.x > radius) || (cords.y > radius)){
Закомментированный код

2023-10-12 13:37 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +std::atomic<size_t> dotsInCircle {0};
Вот это очень плохо, зачем глобальная переменная? Что будет, если я из двух разных потоков позову функцию CircleArea одновременно(ничего хорошего)?

Создавай её внутри функции, и положи в свою структурку ссылку на нее

2023-10-12 13:37 UTC, QElderDelta commented on lab2/include/monte-carlo.hpp
> +}Coordinats;
Правильно - Coordinates

2023-10-12 13:37 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +    for (size_t i = 0; i < (reinterpret_cast<Args *>(input))->dotsPerThread; i++)
Ну ужасно же выглядит, в начале функции объяви
```cpp
const auto& args = *(reinterpret_cast<Args *>(input));
```

2023-10-12 13:37 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +            argsForThread[i].seed = new unsigned int;
Зачем тебе seed создавать в динамической памяти? Почему просто не использовать указатель на seed из структуре(в структуре seed сделать не указателем, а обычной переменной)

2023-10-12 13:37 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +            counter++;
Лучше ++counter))

2023-10-12 13:37 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +    pthread_exit(0);
return nullptr то же самое, но понятнее выглядит

2023-10-12 13:37 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +    dotsInCircle.fetch_add(counter, std::memory_order_relaxed);
А ты прям разбираешься в мемори ордерах?)

2023-10-12 13:37 UTC, QElderDelta commented on tests/lab2_test.cpp
> +    clock_gettime(CLOCK_MONOTONIC, &start);
Используй std::chrono, это штука нечитаемая

2023-10-12 13:37 UTC, QElderDelta commented on tests/lab2_test.cpp
> +    ASSERT_TRUE(area - 1 <= areaMonteCarlo && areaMonteCarlo <= area + 1);
Разбей на два EXPECT_LE

2023-10-12 13:37 UTC, QElderDelta commented on tests/lab2_test.cpp
> +#include <gtest/gtest.h>
Не хватает теста, который проверяет, что разные конфигурации тредов выдают одни и те же результаты

2023-10-12 13:37 UTC, QElderDelta commented on tests/lab2_test.cpp
> +    clock_gettime(CLOCK_MONOTONIC, &start);
Много дублирования кода

2023-10-12 19:35 UTC, L0ckR commented on lab2/include/monte-carlo.hpp
> +#define _USE_MATH_DEFINES
stackoverflow обманушка

2023-10-12 21:11 UTC, L0ckR commented on lab2/CMakeLists.txt
> +# set(THREADS_PREFER_PTHREAD_FLAG ON)
а черт его знает, я проверял соберется ли без

2023-10-12 21:18 UTC, L0ckR commented on lab2/src/monte-carlo.cpp
> +    dotsInCircle.fetch_add(counter, std::memory_order_relaxed);
пойман за руку, как дешевка

2023-10-13 13:43 UTC, QElderDelta approved these changes

2023-10-13 13:43 UTC, QElderDelta commented on lab2/include/monte-carlo.hpp
> +typedef struct{
Некрасивый typedef остался...

2023-10-13 13:43 UTC, QElderDelta commented on lab2/src/monte-carlo.cpp
> +    const auto args = reinterpret_cast<Args *>(input);
Во-первых, auto*. Во-вторых, лучше бы это ссылка была, вместо -> писал бы .

2023-10-13 13:43 UTC, QElderDelta commented on tests/lab2_test.cpp
> +        constexpr int runsCount = 5;
А что с отступами?

2023-10-13 13:43 UTC, QElderDelta commented on tests/lab2_test.cpp
> +        ASSERT_TRUE(area - 1 <= areaMonteCarlo);
А здесь почему не EXPECT_LE?

2023-10-13 13:43 UTC, QElderDelta commented on tests/lab2_test.cpp
> +    std::vector<double> x(12);
12 лучше отдельной константой сделать

2023-10-13 13:43 UTC, QElderDelta commented on tests/lab2_test.cpp
> +    double area = M_PI*(5*5);
constexpr?

2023-10-13 17:54 UTC, merged